blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/StefanIsMe/dsh-updater-plugin/issues
    about: Open an issue with the question label for general questions
